//go:build ignore

// gen.go populates the embed directories from the source tree. Run via:
//
//	make generate
//	go generate ./internal/assets/
//
// Prefer `make generate` (or `make build`, which depends on it). After editing
// chart Chart.yaml dependencies, run `helm dependency update` in
// charts/wolfram-application-server/ before generating so charts/ is current.
//
// This script MUST be run before `go build` in production. The --local flag
// bypasses this requirement for developer iteration.
package main

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/WolframResearch/WAS-Kubernetes/internal/versions"
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fatalf("find repo root: %v", err)
	}

	assetsDir := filepath.Join(repoRoot, "internal", "assets")

	copies := []struct{ src, dst string }{
		{filepath.Join(repoRoot, "infra", "aws", "bootstrap"), filepath.Join(assetsDir, "terraform", "bootstrap")},
		{filepath.Join(repoRoot, "infra", "aws", "stack"), filepath.Join(assetsDir, "terraform", "stack")},
		{filepath.Join(repoRoot, "infra", "azure", "bootstrap"), filepath.Join(assetsDir, "terraform", "azure-bootstrap")},
		{filepath.Join(repoRoot, "infra", "azure", "stack"), filepath.Join(assetsDir, "terraform", "azure-stack")},
		{filepath.Join(repoRoot, "charts", "wolfram-application-server"), filepath.Join(assetsDir, "chart")},
	}

	for _, c := range copies {
		if err := syncDir(c.src, c.dst); err != nil {
			fatalf("sync %s → %s: %v", c.src, c.dst, err)
		}
		fmt.Printf("✓ synced %s → %s\n", c.src, c.dst)
	}

	awsDefault, err := versions.ExtractClusterVersionDefaultFile(
		filepath.Join(repoRoot, "infra", "aws", "stack", "variables.tf"))
	if err != nil {
		fatalf("aws cluster_version: %v", err)
	}
	azureDefault, err := versions.ExtractClusterVersionDefaultFile(
		filepath.Join(repoRoot, "infra", "azure", "stack", "variables.tf"))
	if err != nil {
		fatalf("azure cluster_version: %v", err)
	}
	out := filepath.Join(repoRoot, "internal", "versions", "k8s_cluster_gen.go")
	if err := writeK8sClusterGen(out, awsDefault, azureDefault); err != nil {
		fatalf("write %s: %v", out, err)
	}
	fmt.Printf("✓ wrote %s (aws=%s azure=%s)\n", out, awsDefault, azureDefault)
}

func writeK8sClusterGen(path, awsDefault, azureDefault string) error {
	content := fmt.Sprintf(`// Code generated by go generate ./internal/assets; DO NOT EDIT.

package versions

// AWSClusterK8sDefault is the cluster_version default from infra/aws/stack/variables.tf.
const AWSClusterK8sDefault = %q

// AzureClusterK8sDefault is the cluster_version default from infra/azure/stack/variables.tf.
const AzureClusterK8sDefault = %q
`, awsDefault, azureDefault)
	return os.WriteFile(path, []byte(content), 0644)
}

// syncDir copies src into dst, removing dst first to avoid stale files.
func syncDir(src, dst string) error {
	if err := os.RemoveAll(dst); err != nil {
		return err
	}
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// Skip .terraform/ provider cache — it's platform-specific and large.
		if d.IsDir() && d.Name() == ".terraform" {
			return filepath.SkipDir
		}
		rel, _ := filepath.Rel(src, path)
		dstPath := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(dstPath, 0755)
		}
		return copyFile(path, dstPath)
	})
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	info, err := in.Stat()
	if err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, info.Mode())
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found in any parent directory")
		}
		dir = parent
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen: "+format+"\n", args...)
	os.Exit(1)
}
