// Code generated by go generate ./internal/assets; DO NOT EDIT.

package versions

// AWSClusterK8sDefault is the cluster_version default from infra/aws/stack/variables.tf.
const AWSClusterK8sDefault = "1.36"

// AzureClusterK8sDefault is the cluster_version default from infra/azure/stack/variables.tf.
const AzureClusterK8sDefault = "1.36"
