apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-persistent
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.0"
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: kafka-standardssd-xfs
        size: 10Gi
        deleteClaim: false
    template:
      pod:
        securityContext:
          fsGroup: 1001
          fsGroupChangePolicy: OnRootMismatch
  zookeeper:
    replicas: 3
    jvmOptions:
      javaSystemProperties:
        - name: zookeeper.ssl.hostnameVerification
          value: "false"
        - name: zookeeper.ssl.quorum.hostnameVerification
          value: "false"
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    storage:
      type: persistent-claim
      class: kafka-standardssd-xfs
      size: 10Gi
      deleteClaim: false
    template:
      pod:
        securityContext:
          fsGroup: 1001
          fsGroupChangePolicy: OnRootMismatch
  entityOperator:
    topicOperator: {}
    userOperator: {}
