apiVersion: v1
kind: Service
metadata:
  name: endpoint-manager
  namespace: {{ .Values.namespace.name }}
  labels:
    app: endpoint-manager
    app.kubernetes.io/component: endpoint-manager
    {{- include "was.labels" . | nindent 4 }}
spec:
  selector:
    app: endpoint-manager
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085
