apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awes-logs
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: storage
    {{- include "was.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.logsSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resources-logs
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: storage
    {{- include "was.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.logsSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: endpoint-logs
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/component: storage
    {{- include "was.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.logsSize }}
