apiVersion: v1
kind: Service
metadata:
  name: resource-manager
  namespace: {{ .Values.namespace.name }}
  labels:
    app: resource-manager
    app.kubernetes.io/component: resource-manager
    {{- include "was.labels" . | nindent 4 }}
spec:
  selector:
    app: resource-manager
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
